### ISSUE TITLE
FYI BLE Protocol

### ISSUE THREAD

**Issue by DorianRudolph** [ph4r05/ph4-walkingpad#5]
Hi, I also independently reverse engineered the WalkingPad protocol. I think I might have a few additional fields. For example, the WalkingPad can store multiple records in memory, which it seems it not handled in this app. If you are interested, you can check out https://github.com/DorianRudolph/QWalkingPad/blob/master/Protocol.h

**Comment by DorianRudolph** [comment]
Ah, very cook project nonetheless. Would have saved my quite a bit of time if I  had found your project when I implemented mine. Also, it's totally fine to use my code as reference to reimplement the protocol, that does not fall under GPL.

**Comment by ph4r05** [comment]
Likewise 😄 the reverse engineering took some time and effort. Anyway, thanks for linking your project! I will add it to the readme as related work.

Ad GPL - I find it sometimes difficult to tell where the boundary of the license is ans what is derived work already and what not. I guess one would have to read the code, write down bit fields on paper and reimplement it from the scratch, without looking on the code. To be safe from GPL virality. 

Thanks for your work!

**Comment by ph4r05** [comment]
added to readme
