### ISSUE TITLE
Errors when running script

### ISSUE THREAD

**Issue by haivala** [ph4r05/ph4-walkingpad#8]
Thank you for great software! Using this with walking pad DTM100i and arch linux. Never used the phone app.
The program connects to the pad and writes stats but I cannot control the pad with it.
I have these errors reported about every half a minute but randomly. The pad was in standby mode when i started the script and then I tried to control it with `start` and `speed 3`but I had to use the remote to actually start it. 

```
A message handler raised an exception: bytearray index out of range.
Traceback (most recent call last):
  File "/.local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 668, in _process_message
    result = handler(msg)
  File "/.local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 1018, in _parse_msg
    self._notification_callbacks[message.path](
  File "/.local/lib/python3.10/site-packages/ph4_walkingpad/pad.py", line 232, in notif_handler
    m = WalkingPadCurStatus.from_data(data)
  File "/.local/lib/python3.10/site-packages/ph4_walkingpad/pad.py", line 157, in from_data
    m.load_from(cmd)
  File "/.local/lib/python3.10/site-packages/ph4_walkingpad/pad.py", line 138, in load_from
    self.belt_state = cmd[2]
IndexError: bytearray index out of range
```
and
```
A message handler raised an exception: bytearray index out of range.
Traceback (most recent call last):
  File "/.local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 668, in _process_message
    result = handler(msg)
  File "/.local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 1018, in _parse_msg
    self._notification_callbacks[message.path](
  File "/.local/lib/python3.10/site-packages/ph4_walkingpad/pad.py", line 232, in notif_handler
    m = WalkingPadCurStatus.from_data(data)
  File "/.local/lib/python3.10/site-packages/ph4_walkingpad/pad.py", line 157, in from_data
    m.load_from(cmd)
  File "/.local/lib/python3.10/site-packages/ph4_walkingpad/pad.py", line 143, in load_from
    self.steps = WalkingPad.byte2int(cmd[11:])
  File "/.local/lib/python3.10/site-packages/ph4_walkingpad/pad.py", line 115, in byte2int
    return sum([(val[i] << (8 * (width - 1 - i))) for i in range(width)])
  File "/.local/lib/python3.10/site-packages/ph4_walkingpad/pad.py", line 115, in <listcomp>
    return sum([(val[i] << (8 * (width - 1 - i))) for i in range(width)])
IndexError: bytearray index out of range
```
am I missing something?

**Comment by ph4r05** [comment]
I have no access to this belt type, so in order to reverse engineer the protocol we would need couple of messages being exchanged between app and the belt. Android application is ideal for it.

https://github.com/ph4r05/ph4-walkingpad#easy-way---android-logs

**Comment by haivala** [comment]
I really don't want to install the android app.

I have been using this program to collect the stats and it has been enough for that. Just wondering should there be a way to use only the connecting and stats part of the program as those work for my pad. As I said I use the remote to control it.

**Comment by haivala** [comment]
Yes it works for the stats collection and there is times when the stats say
`"ccal": null, "ccal_net": null, "ccal_sum": null, "ccal_net_sum": null`
but then on right after it works again like this:
```
{"time": 211, "dist": 13, "steps": 317, "speed": 30, "app_speed": 7, "belt_state": 1, "controller_button": 0, "manual_mode": 1, "raw": "f8a2011e010000d300000d00013d07000000e7fd", "rec_time": 1649253095.8210037, "pid": "user", "ccal": null, "ccal_net": null, "ccal_sum": null, "ccal_net_sum": null}
{"time": 212, "dist": 14, "steps": 317, "speed": 30, "app_speed": 7, "belt_state": 1, "controller_button": 0, "manual_mode": 1, "raw": "f8a2011e010000d400000e00013d07000000e9fd", "rec_time": 1649253095.8585336, "pid": "user", "ccal": 0.072, "ccal_net": 0.049, " ccal_sum": 13.453, "ccal_net_sum": 8.722}
```

**Comment by ph4r05** [comment]
ah, in that case, I've pushed an update, you can try running it with `--ignore-bad-packets`, it should silence those errors you are getting. 

It is just matter of logging, those unsupported packets won't be decoded, just discarded. But if you get reasonable info anyway, this should do the job.

**Comment by haivala** [comment]
Seem to be working but it gives this error on startup:
```
Executing <Task pending name='Task-1' coro=<WalkingPadControl.main() running at /.local/lib/python3.10/site-packages/ph4_walkingpad/main.py:375> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_read_done(10, handle=<Handle BaseS...events.py:254>)(), Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184] created at /usr/lib/python3.10/asyncio/tasks.py:636> took 0.114 seconds
```

**Comment by haivala** [comment]
Now it suddenly stopped which it has never done before

**Comment by ph4r05** [comment]
Hmm, use this at your own risk 😅  do not leave belt powered on unattended, etc.

The stats collection works in a way it sends periodically stats prompt message (each 500ms) to the belt, i.e., `[247, 162, 0, 0, 162, 253]`. Belt responds with the latest stats (including steps). 

As this app was not tested with the belt, it can have unknown protocol and belt can interpret prompt message in a different way. 

Maybe try using `--stats 1500` to ask for stats each 1.5 second.

**Comment by haivala** [comment]
yeah. I just noticed first time that it seems like the peep comes from changing from manual speed mode to automatic. Without the connection to the script it cannot be changed in the middle of walk. (haven't used it for a long time without the connection so I'm not sure.)
